import 'controller/logout_modal_controller.dart';import 'package:flutter/material.dart';import 'package:nguyen_manh_hung_s_application1/core/app_export.dart';import 'package:nguyen_manh_hung_s_application1/widgets/custom_button.dart';
// ignore_for_file: must_be_immutable
class LogoutModalBottomsheet extends StatelessWidget {LogoutModalBottomsheet(this.controller);

LogoutModalController controller;

@override Widget build(BuildContext context) { return SingleChildScrollView(child: Container(width: double.infinity, decoration: AppDecoration.outlineGray100.copyWith(borderRadius: BorderRadiusStyle.customBorderTL40), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.center, mainAxisAlignment: MainAxisAlignment.start, children: [Container(height: getVerticalSize(3.00), width: getHorizontalSize(38.00), margin: getMargin(left: 24, top: 8, right: 24), decoration: BoxDecoration(color: ColorConstant.gray300, borderRadius: BorderRadius.circular(getHorizontalSize(1.50)))), Padding(padding: getPadding(left: 24, top: 29, right: 24), child: Text("lbl_logout".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtUrbanistRomanBold24RedA200)), Container(height: getVerticalSize(1.00), width: getHorizontalSize(380.00), margin: getMargin(left: 24, top: 23, right: 24), decoration: BoxDecoration(color: ColorConstant.gray200)), Padding(padding: getPadding(left: 24, top: 27, right: 24), child: Text("msg_are_you_sure_yo".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtUrbanistRomanBold20Gray800)), Container(margin: getMargin(left: 24, top: 24, right: 24, bottom: 48), decoration: BoxDecoration(borderRadius: BorderRadius.circular(getHorizontalSize(16.00))), child: Row(mainAxisAlignment: MainAxisAlignment.start, crossAxisAlignment: CrossAxisAlignment.center, mainAxisSize: MainAxisSize.max, children: [CustomButton(width: 184, text: "lbl_cancel".tr, variant: ButtonVariant.FillDeeporange50, shape: ButtonShape.RoundedBorder16, padding: ButtonPadding.PaddingAll18, fontStyle: ButtonFontStyle.UrbanistRomanBold16DeeporangeA401, onTap: onTapCancel), CustomButton(width: 184, text: "lbl_yes_logout".tr, margin: getMargin(left: 12), variant: ButtonVariant.OutlineDeeporangeA400351_2, shape: ButtonShape.RoundedBorder16, padding: ButtonPadding.PaddingAll18, fontStyle: ButtonFontStyle.UrbanistRomanBold16)]))]))); } 
onTapCancel() { Get.back(); } 
 }
