import '../switch_account_bottomsheet/widgets/switch_account_item_widget.dart';import 'controller/switch_account_controller.dart';import 'models/switch_account_item_model.dart';import 'package:flutter/material.dart';import 'package:nguyen_manh_hung_s_application1/core/app_export.dart';import 'package:nguyen_manh_hung_s_application1/widgets/custom_icon_button.dart';
// ignore_for_file: must_be_immutable
class SwitchAccountBottomsheet extends StatelessWidget {SwitchAccountBottomsheet(this.controller);

SwitchAccountController controller;

@override Widget build(BuildContext context) { return SingleChildScrollView(child: Container(width: double.infinity, decoration: AppDecoration.outlineGray100.copyWith(borderRadius: BorderRadiusStyle.customBorderTL40), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Container(height: getVerticalSize(3.00), width: getHorizontalSize(38.00), margin: getMargin(left: 24, top: 8, right: 24), decoration: BoxDecoration(color: ColorConstant.gray300, borderRadius: BorderRadius.circular(getHorizontalSize(1.50))))), Align(alignment: Alignment.center, child: Padding(padding: getPadding(left: 24, top: 26, right: 24), child: Text("lbl_switch_account".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtUrbanistRomanBold24))), Align(alignment: Alignment.center, child: Container(height: getVerticalSize(1.00), width: getHorizontalSize(380.00), margin: getMargin(left: 24, top: 26, right: 24), decoration: BoxDecoration(color: ColorConstant.gray200))), Align(alignment: Alignment.center, child: Padding(padding: getPadding(left: 24, top: 23, right: 24), child: Obx(() => ListView.builder(physics: BouncingScrollPhysics(), shrinkWrap: true, itemCount: controller.switchAccountModelObj.value.switchAccountItemList.length, itemBuilder: (context, index) {SwitchAccountItemModel model = controller.switchAccountModelObj.value.switchAccountItemList[index]; return SwitchAccountItemWidget(model);})))), Padding(padding: getPadding(left: 24, top: 24, right: 24, bottom: 36), child: Row(mainAxisAlignment: MainAxisAlignment.start, crossAxisAlignment: CrossAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomIconButton(height: 60, width: 60, padding: IconButtonPadding.PaddingAll21, onTap: () {onTapBtntf();}, child: CommonImageView(svgPath: ImageConstant.imgClose60X60)), Padding(padding: getPadding(left: 20, top: 20, bottom: 21), child: Text("lbl_add_account".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtUrbanistRomanBold18Gray900))]))]))); } 
onTapBtntf() { Get.back(); } 
 }
